service.type: ClusterIP
service.ports: [ 6379 ]
configuration: |
  global
    daemon
    maxconn 256

  defaults
    mode tcp
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

  frontend redis
    bind *:6379
    default_backend redis-primary

  backend redis-primary
    mode tcp
    balance first
    option tcp-check
    tcp-check send info\ replication\r\n
    tcp-check expect string role:master
    server redis0 redis-redis-cluster-0.redis-redis-cluster-headless:6379 check
    server redis1 redis-redis-cluster-1.redis-redis-cluster-headless:6379 check
    server redis2 redis-redis-cluster-2.redis-redis-cluster-headless:6379 check
    server redis3 redis-redis-cluster-3.redis-redis-cluster-headless:6379 check
    server redis4 redis-redis-cluster-4.redis-redis-cluster-headless:6379 check
    server redis5 redis-redis-cluster-5.redis-redis-cluster-headless:6379 check
