apiVersion: v1
kind: Service
metadata:
  annotations:
    redis.opstreelabs.in: "true"
    redis.opstreelabs.instance: testcluster
  labels:
    app: testcluster-leader
    redis_setup_type: cluster
    role: leader
  name: testcluster-leader-lb
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: redis-exporter
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: testcluster-leader
    redis_setup_type: cluster
    role: leader
  sessionAffinity: None
  type: LoadBalancer